### ISSUE TITLE
Webpack module?

### ISSUE THREAD

**Issue by IngwiePhoenix** [davidkpiano/sassport#5]
Has someone made a WebPack loader yet?

If not, then the world is missing something awesome - and if so, I'll go ahead and build one. I just don't want to re-invent the wheel, y'know. :)

**Comment by davidkpiano** [comment]
@IngwiePhoenix If you could build one, that would be great! I'll contribute in any way that I can.

**Comment by IngwiePhoenix** [comment]
I'm working on it ATM. :)

**Comment by IngwiePhoenix** [comment]
I am as far as to having half of the original tests passing. The problem just seems to be one I can not identify:

```
  30 passing (1s)
  26 pending
  26 failing

  1) sassport-loader basic should compile simple sass without errors (async) (scss):
     Uncaught TypeError: Cannot read property '_beforeRender' of undefined
      at render (node_modules/sassport/dist/index.js:279:11)
      at node_modules/async/lib/async.js:945:13
      at Immediate.q.process [as _onImmediate] (node_modules/async/lib/async.js:913:25)
```

It is the same error everywhere. Has me guessing that it isn't even my fault. :)

**Comment by davidkpiano** [comment]
@IngwiePhoenix It seems like `async.queue` is actually messing with the `this` binding of the Sassport instance.

This is the line that's giving problems: https://github.com/IngwiePhoenix/sassport-loader/blob/master/index.js#L220

With this modification, the tests will pass:
```js
    // Sassport instance
    var sassportInstance = sassport(opt.modules);

    // Define the job queue...
    var asyncSassJobQueue = async.queue(sassportInstance.render.bind(sassportInstance), threadPoolSize - 1);
```

**Comment by IngwiePhoenix** [comment]
Roger that! On it.

**Comment by IngwiePhoenix** [comment]
Yup!

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/sassport-loader $ npm run test

> sass-loader@0.1.0 pretest /Users/Ingwie/Work/sassport-loader
> node test/tools/runCreateSpec.js


> sass-loader@0.1.0 test /Users/Ingwie/Work/sassport-loader
> mocha -R spec



  sassport-loader
    basic
      ✓ should compile simple sass without errors (sync) (scss)
      ✓ should compile simple sass without errors (sync) (sass)
      ✓ should compile simple sass without errors (async) (scss) (73ms)
      ✓ should compile simple sass without errors (async) (sass)
    imports
      ✓ should resolve imports correctly (sync) (scss)
      ✓ should resolve imports correctly (sync) (sass)
      ✓ should resolve imports correctly (async) (scss)
      ✓ should resolve imports correctly (async) (sass)
      ✓ should pass with multiple imports (sync) (scss)
      ✓ should pass with multiple imports (sync) (sass)
      ✓ should pass with multiple imports (async) (scss)
      ✓ should pass with multiple imports (async) (sass)
      ✓ should resolve imports from other language style correctly (sync) (scss)
      ✓ should resolve imports from other language style correctly (sync) (sass)
      ✓ should resolve imports from other language style correctly (async) (scss)
      ✓ should resolve imports from other language style correctly (async) (sass)
      ✓ should resolve imports from another directory declared by includePaths correctly (sync) (scss)
      ✓ should resolve imports from another directory declared by includePaths correctly (sync) (sass)
      ✓ should resolve imports from another directory declared by includePaths correctly (async) (scss)
      ✓ should resolve imports from another directory declared by includePaths correctly (async) (sass)
      ✓ should not resolve CSS imports (sync) (scss)
      ✓ should not resolve CSS imports (sync) (sass)
      ✓ should not resolve CSS imports (async) (scss)
      ✓ should not resolve CSS imports (async) (sass)
      ✓ should prefer _.scss over _.sass (sync) (scss)
      ✓ should prefer _.scss over _.sass (sync) (sass)
      ✓ should prefer _.scss over _.sass (async) (scss)
      ✓ should prefer _.scss over _.sass (async) (sass)
      ✓ should prefer _.sass over _.css (sync) (scss)
      ✓ should prefer _.sass over _.css (sync) (sass)
      ✓ should prefer _.sass over _.css (async) (scss)
      ✓ should prefer _.sass over _.css (async) (sass)
      ✓ should prefer _.css over .scss (sync) (scss)
      ✓ should prefer _.css over .scss (sync) (sass)
      ✓ should prefer _.css over .scss (async) (scss)
      ✓ should prefer _.css over .scss (async) (sass)
      ✓ should prefer .scss over .sass (sync) (scss)
      ✓ should prefer .scss over .sass (sync) (sass)
      ✓ should prefer .scss over .sass (async) (scss)
      ✓ should prefer .scss over .sass (async) (sass)
      ✓ should prefer .sass over .css (sync) (scss)
      ✓ should prefer .sass over .css (sync) (sass)
      ✓ should prefer .sass over .css (async) (scss)
      ✓ should prefer .sass over .css (async) (sass)
      ✓ should prefer explicit imports over auto-resolving (sync) (scss)
      ✓ should prefer explicit imports over auto-resolving (sync) (sass)
      ✓ should prefer explicit imports over auto-resolving (async) (scss)
      ✓ should prefer explicit imports over auto-resolving (async) (sass)
      ✓ should compile bootstrap-sass without errors (sync) (scss) (309ms)
      ✓ should compile bootstrap-sass without errors (sync) (sass) (307ms)
      ✓ should compile bootstrap-sass without errors (async) (scss) (352ms)
      ✓ should compile bootstrap-sass without errors (async) (sass) (349ms)
    errors
      ✓ should output understandable errors in entry files
      ✓ should output understandable errors of imported files
      ✓ should output understandable errors when a file could not be found
      ✓ should not auto-resolve imports with explicit file names

  scss spec
    - bootstrap-sass.css should not have been changed
    - import-css.css should not have been changed
    - import-include-paths.css should not have been changed
    - import-order-1.css should not have been changed
    - import-order-2.css should not have been changed
    - import-order-3.css should not have been changed
    - import-order-4.css should not have been changed
    - import-order-5.css should not have been changed
    - import-order-6.css should not have been changed
    - import-other-style.css should not have been changed
    - imports.css should not have been changed
    - language.css should not have been changed
    - multiple-imports.css should not have been changed

  sass spec
    - bootstrap-sass.css should not have been changed
    - import-css.css should not have been changed
    - import-include-paths.css should not have been changed
    - import-order-1.css should not have been changed
    - import-order-2.css should not have been changed
    - import-order-3.css should not have been changed
    - import-order-4.css should not have been changed
    - import-order-5.css should not have been changed
    - import-order-6.css should not have been changed
    - import-other-style.css should not have been changed
    - imports.css should not have been changed
    - language.css should not have been changed
    - multiple-imports.css should not have been changed


  56 passing (2s)
  26 pending


> sass-loader@0.1.0 posttest /Users/Ingwie/Work/sassport-loader
> jshint index.js test

Ingwie@Ingwies-Macbook-Pro.local ~/W/sassport-loader $ echo $status
0
```

Going to push to Git. You can look over it to see if I forgot anything in the readme. :3

**Comment by IngwiePhoenix** [comment]
Hah, I saw you star it :) So I bet it is all good to go on NPM and such?

**Comment by davidkpiano** [comment]
If the tests are all green, I don't see why not!

**Comment by IngwiePhoenix** [comment]
Yup - as you can see, they pass.

Oookay! Then I'll put this to NPM and you can link to that in the README. The link will be http://npmjs.com/sassport-loader

**Comment by IngwiePhoenix** [comment]
Put it in, and it works. Using it in my main project now. :)

**Comment by davidkpiano** [comment]
Fantastic, @IngwiePhoenix ! I'll definitely be using this as well - I use Webpack a lot and have only been able to dogfood Sassport outside of Webpack.

I'll add a link to it on the README.md. Thanks! :confetti_ball:

**Comment by IngwiePhoenix** [comment]
Thanks! I'll make sure to improve it to make passing options even better and more confortable, so that as many as possible of Sassport's features will be usable. For now, it supports the basics, and that already helps a lot.

Enjoy! :)
